# Generated by Django 3.1.3 on 2020-11-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cat_href',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='href'),
        ),
    ]
